import { StyleSheet } from "react-native";
import { colors } from "../../Theme/GlobalTheme";

const styles = StyleSheet.create({
    container:{
        flex:1,
        width:'100%',
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'white',
    },
    heading:{
        color:colors.blue,
        fontSize:32,
        fontFamily:'Gilroy-Bold',
        alignSelf:'flex-start',
        marginLeft:'5%',
        marginTop:'10%'
    },
    otpTextContainer:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        width:'98%',
        paddingRight:'2%',
        top:'1%',
    },
    change:{
        fontSize:12,
        fontFamily:'Gilroy-SemiBold',
        color:colors.blue,
    },
    phoneContainer:{
        flexDirection:'row',
        width:'90%',
        alignItems:'center',
        justifyContent:'space-between',
        marginLeft:'3%'
    },
    phoneInput:{
        borderWidth:1,
        width:'67%',
        borderColor:colors.grey,
        borderRadius:3,
        height:47,
        fontSize:14,
        fontFamily:'Gilroy-Medium',
        paddingLeft:15
    },
    numberHeading:{
        width:'90%',
        fontSize:12,
        fontFamily:'Gilroy-SemiBold',
        marginTop:'7%',
        marginBottom:'2%',
        color:colors.darkGrey,
        paddingLeft:'2%'
    },
    bottomContainer:{
        flexDirection:'row',
        marginTop:'10%'
    },
    bottomText:{
        color:colors.grey,
        fontSize:14,
        fontFamily:'Gilroy-regular'
    },
    signup:{
        color:colors.blue,
        fontFamily:'Gilroy-SemiBold',
        fontSize:14
    },
    termContainer:{
        width:'95%',
        flexDirection:'row',
        alignItems:'center',
        marginLeft:'3%'
    },
    termText:{
        fontSize:12, 
        fontFamily:'Gilroy-Regular',
        color:colors.darkGrey,
    },
    term:{
        fontSize:12,
        fontFamily:'Gilroy-SemiBold',
        color:colors.blue,
    }
})

export default styles;